name: Scraper Viager

on:
  schedule:
    - cron: '0 9 * * *'  # 11h Paris
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installer dépendances système
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libx11-xcb1 \
            libxcb-dri3-0 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libasound2t64

      - name: Installer Python
        run: |
          pip install pandas playwright folium requests
          playwright install --with-deps

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python carte_finale_totale.py

      - name: Commit historique
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add historique_ids.csv
          git commit -m "update historique" || echo "no changes"
          git push
